In [2]:
import pandas as pd
import nltk
import re

from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

# one hot encoding
from tensorflow.keras.preprocessing.text import one_hot


In [5]:
stemmer = PorterStemmer()
lemmatize = WordNetLemmatizer()


In [ ]:
paragraph = """
Chief Bola Ahmed Adekunle Tinubu GCFR (born 29 March 1952) is a Nigerian politician who is the 16th and current president of Nigeria.[1] He was the governor of Lagos State from 1999 to 2007; and senator for Lagos West in the Third Republic.

Tinubu spent his early life in southwestern Nigeria and later moved to the United States where he studied accounting at Chicago State University. He returned to Nigeria in the early 1990s and was employed by Mobil Nigeria as an accountant, before entering politics as a Lagos West senatorial candidate in 1992 under the banner of the Social Democratic Party. After dictator Sani Abacha dissolved the Senate in 1993, Tinubu became an activist campaigning for the return of democracy as a part of the National Democratic Coalition movement.

In the first post-transition Lagos State gubernatorial election, Tinubu won by a wide margin as a member of the Alliance for Democracy. Four years later, he won re-election to a second term. After leaving office in 2007, he played a key role in the formation of the All Progressives Congress in 2013. In 2023, he was elected president of Nigeria.
"""

In [7]:
# tokenization
nltk.download('stopwords')
nltk.download('punkt')

# sentences = nltk.sent_tokenize(paragraph)

[nltk_data] Downloading package stopwords to C:\Users\ACER-
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\ACER-
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review=review.lower()
    corpus.append(review)

In [ ]:
# to apply stemming
for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))

In [ ]:
stopwords.words('english')
nltk.download('wordnet')


In [ ]:
# paragraph = []

# for i in range(len(sentences)):
#     review = re.sub('[^a-zA-Z]', ' ', sentences[i])
#     review = review.lower()
#     review = review.split()
#     review = [lemmatize.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
#     review = ' '.join(review) 
#     paragraph.append(review)

In [ ]:
# to apply lemmatizer

for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatize.lemmatize(word))

In [ ]:
# bag of words

cv = CountVectorizer(binary=True, ngram_range=(3,3))

In [ ]:
X = cv.fit_transform(corpus)
cv.vocabulary_
sorted(cv.vocabulary_.items())


In [ ]:
X[0].toarray()

In [ ]:
corpus

In [ ]:
## TFIDF
# from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(ngram_range=(1,1), max_features=10)
X = tv.fit_transform(corpus)

In [ ]:
X[0].toarray()

In [164]:
# READ CSV
spam = pd.read_csv('spam_ham.csv', sep='\t', names=['labels', 'message'])

In [ ]:
# APPLY STEMMER
corpus_stem = []

for i in range(0, len(spam)):
    review = re.sub('[^a-zA-Z0-9]', ' ', spam['message'][i])
    review = review.lower()
    review = review.split()
    review = [stemmer.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review) 
    corpus_stem.append(review)

In [ ]:
# bag of words
cv = CountVectorizer(max_features=2500,binary=True)
X = cv.fit_transform(corpus_stem).toarray()

In [89]:
y = pd.get_dummies(spam['labels'])
y = y.iloc[:, 1].astype(int)

In [91]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int32

In [ ]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
mnb = MultinomialNB().fit(X_train, y_train)
# prediction
y_pred = mnb.predict(X_test)
accuracy_score(y_pred, y_test)

In [ ]:
# classification_report(y_pred, y_test)
confusion_matrix(y_pred, y_test)

In [ ]:
# TFIDF

tv = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X = tv.fit_transform(corpus_stem).toarray()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
mnb = MultinomialNB().fit(X_train, y_train)
y_pred = mnb.predict(X_test)
accuracy_score(y_pred, y_test)

In [ ]:
# random forest
from sklearn.ensemble import RandomForestClassifier

In [ ]:
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
accuracy_score(y_pred, y_test)


### Word2vec

In [ ]:
%pip install gensim

In [21]:
import numpy as np

In [ ]:
# import gensim.downloader as api

# wv = api.load('word2vec-google-news-300')

In [165]:
corpus = []

for i in range(0, len(spam)):
    review = re.sub('[^a-zA-Z0-9]', ' ', spam['message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatize.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review) 
    corpus.append(review)

In [203]:
corpus[:5]

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry question std txt rate c apply 08452810075over18',
 'u dun say early hor u c already say',
 'nah think go usf life around though']

In [ ]:
y

In [109]:
y = pd.get_dummies(y).iloc[:, 1].astype(int)

In [110]:
import gensim
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [174]:
# words = []
# for i in corpus:
#     sent_token = sent_tokenize(i)
#     for i in sent_token:
#         words.append(simple_preprocess(i))

In [195]:
words = []
for i in corpus:
    sent_token = sent_tokenize(i)
    words.append(simple_preprocess(i))
        

In [197]:
len(words)

5565

In [198]:
len(words)

5565

In [154]:
model = gensim.models.Word2Vec(words, window=5,min_count=2)

In [157]:
model.wv.index_to_key

315

In [158]:
model.corpus_count

5572

In [142]:
model.epochs

5

In [144]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    # sent = [word for word in doc if word in model.mv.index_to_key]
    # print(sent)
    
    return np.mean([model.wv[word] for word in words if word in model.wv.index_to_key], axis=0)


In [27]:
from tqdm import tqdm

In [162]:
X = []

for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|          | 0/5572 [00:00<?, ?it/s]c:\Users\ACER-PC\Desktop\Z\BA_nltk\.venv\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\ACER-PC\Desktop\Z\BA_nltk\.venv\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5572/5572 [07:49<00:00, 11.87it/s]


In [41]:
X_new =  np.array(X, dtype=object)

In [45]:
X_new[0]

array([-0.0572608 ,  0.2736493 ,  0.02597114,  0.01283087,  0.01862401,
       -0.38753533,  0.06568547,  0.51432174, -0.14124586, -0.12946813,
       -0.10796515, -0.35931024, -0.0528903 ,  0.08321051,  0.07744681,
       -0.24833035,  0.00578281, -0.3561922 , -0.01361859, -0.40739238,
        0.15922056,  0.04068476,  0.11397326, -0.09942146, -0.11764296,
        0.03255244, -0.24111311, -0.2693658 , -0.241899  ,  0.07553742,
        0.31912678, -0.00396283,  0.11117529, -0.17404239, -0.09871449,
        0.2199322 , -0.06809594, -0.23408274, -0.14690335, -0.49812046,
       -0.00717556, -0.27797118, -0.05698733,  0.03035105,  0.21321188,
       -0.18032382, -0.17816865,  0.0175348 ,  0.10231765,  0.1819616 ,
        0.12994821, -0.20816559, -0.03378843, -0.04842072, -0.18076712,
        0.11473767,  0.13337092,  0.03621004, -0.24753475, -0.02266791,
        0.02906995,  0.13778256, -0.11427843,  0.04078652, -0.36477742,
        0.32023242,  0.11158089,  0.21156524, -0.33866885,  0.35

### TENSORFLOW

In [199]:
import tensorflow as tf

In [200]:
# tensorflow version
print(tf.__version__)

2.13.0


In [254]:
jet = ['go jurong point crazy available bugis n great',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts 21st may  ',
 'u dun say early hor u c already say',
 'nah think go usf life around though']

In [230]:
#  vocabulary size
voc_size = 20000

In [258]:
ohe = [one_hot(words, voc_size) for words in jet]

In [256]:
print(ohe)

[[8101, 18232, 16013, 9412, 8453, 1284, 9778, 1843], [1022, 9959, 10345, 3091, 11908, 962], [3942, 17683, 12474, 666, 11071, 3125, 271, 7263, 17484, 18680, 15243], [11908, 2133, 2156, 14758, 8484, 11908, 5829, 10351, 2156], [369, 12479, 8101, 15707, 13015, 17367, 9865]]


In [223]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [239]:
# pre padding
max_len = 14
embedded_doc = pad_sequences(ohe, padding='pre', maxlen=max_len)
print(embedded_doc)

[[    0     0     0     0     0     0  8101 18232 16013  9412  8453  1284
   9778  1843]
 [    0     0     0     0     0     0     0     0  1022  9959 10345  3091
  11908   962]
 [    0     0  3942 17683 12474   666 11071  3125   271  7263 17484 18680
  15243  5718]
 [    0     0     0     0     0 11908  2133  2156 14758  8484 11908  5829
  10351  2156]
 [    0     0     0     0     0     0     0   369 12479  8101 15707 13015
  17367  9865]]


In [240]:
# dimension
dim = 10

In [242]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=max_len))
model.compile('adam', 'mse')



In [243]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 14, 10)            200000    
                                                                 
Total params: 200000 (781.25 KB)
Trainable params: 200000 (781.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [245]:
print(model.predict(embedded_doc))

1/1 [==============================] - 1s 917ms/step
[[ 1.37027390e-02  7.50728697e-03 -1.91537291e-03  2.25561298e-02
  -4.65618260e-02  7.38807768e-03 -3.20731774e-02  2.13506483e-02
  -3.37979421e-02 -1.23065338e-02]
 [ 1.37027390e-02  7.50728697e-03 -1.91537291e-03  2.25561298e-02
  -4.65618260e-02  7.38807768e-03 -3.20731774e-02  2.13506483e-02
  -3.37979421e-02 -1.23065338e-02]
 [-1.84089169e-02  3.16628069e-03  4.81788255e-02  1.79197080e-02
  -2.31021885e-02  3.51349972e-02 -5.32878563e-03  2.62005590e-02
  -4.69735973e-02 -1.19806640e-02]
 [-1.44460201e-02 -2.73765083e-02 -1.52546056e-02  4.76735272e-02
   4.69791889e-03 -1.02108940e-02  4.84446920e-02  1.51384510e-02
  -4.74895947e-02 -4.49028127e-02]
 [ 1.84535980e-03 -4.27164882e-03  3.01960856e-03 -9.81173664e-03
  -5.98663092e-03  4.48032655e-02 -4.50769812e-03 -3.84693518e-02
  -1.52222142e-02  8.34927708e-03]
 [-7.14976713e-03 -4.59748283e-02  2.72828974e-02  3.95735838e-02
  -3.24606076e-02 -4.51539829e-03  6.97492436e

In [246]:
embedded_doc[2]

array([    0,     0,  3942, 17683, 12474,   666, 11071,  3125,   271,
        7263, 17484, 18680, 15243,  5718])

In [ ]:
model.predict(embedded_doc)[2]

In [260]:
sentence = [
    'the edit is nice',
    'the format is intact',
    'an excellent invoice',
    'a graphic designer'
]

In [269]:
voca_size = 1000
dimension = 8

encod = [one_hot(word, voca_size) for word in sentence]
encod

[[682, 238, 642, 817], [682, 161, 642, 851], [124, 765, 443], [327, 493, 967]]

In [268]:
sent_len = 6

embededd = pad_sequences(encod, padding='post', maxlen=sent_len)
print(embededd)

[[682 238 642 817   0   0]
 [682 161 642 851   0   0]
 [124 765 443   0   0   0]
 [327 493 967   0   0   0]]


In [271]:
model = Sequential()
model.add(Embedding(voca_size, dimension,input_length=sent_len))
model.compile('adam', 'mse')

In [272]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 6, 8)              8000      
                                                                 
Total params: 8000 (31.25 KB)
Trainable params: 8000 (31.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [274]:
model.predict(embededd)[1]

1/1 [==============================] - 0s 234ms/step


array([[ 0.01730249, -0.02905182, -0.04203447,  0.04622216,  0.03759099,
        -0.03445238,  0.04127964, -0.03031659],
       [ 0.00340147, -0.02760332, -0.03287043, -0.0456552 ,  0.01825352,
         0.01187756,  0.03332193, -0.03357146],
       [ 0.04581827,  0.00497971,  0.01739368,  0.01423415,  0.0204906 ,
         0.03918267, -0.00315655,  0.0364134 ],
       [-0.00851937,  0.02483142, -0.03257564,  0.04078094,  0.01232474,
         0.03391645, -0.0161798 , -0.01858059],
       [-0.02053428,  0.0177946 , -0.01511121, -0.01588248,  0.00129557,
        -0.01895362,  0.02527023,  0.04015435],
       [-0.02053428,  0.0177946 , -0.01511121, -0.01588248,  0.00129557,
        -0.01895362,  0.02527023,  0.04015435]], dtype=float32)